"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-04 19:47:36.329867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cpa_license_ref', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_organization_id'), 'clients', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('org_admin', 'cpa', 'ai_intake', 'ai_reconciliation', 'ai_copilot', 'ai_reporting', name='user_role'), nullable=False),
    sa.Column('is_service_account', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.Enum('human', 'ai_service', 'system', name='actor_type'), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_client_id'), 'audit_events', ['client_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_table('client_accounting_profiles',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('coa_template', sa.String(length=64), nullable=False),
    sa.Column('materiality_threshold', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payroll_provider', sa.String(length=128), nullable=True),
    sa.Column('revenue_model', sa.String(length=255), nullable=True),
    sa.Column('policy_approved_by', sa.UUID(), nullable=True),
    sa.Column('policy_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['policy_approved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_accounting_profiles_client_id'), 'client_accounting_profiles', ['client_id'], unique=True)
    op.create_table('engagements',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('service_tier', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engagements_client_id'), 'engagements', ['client_id'], unique=False)
    op.create_table('gl_accounts',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.Enum('asset', 'liability', 'equity', 'revenue', 'expense', name='gl_account_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'code', name='uq_client_gl_code')
    )
    op.create_index(op.f('ix_gl_accounts_client_id'), 'gl_accounts', ['client_id'], unique=False)
    op.create_table('source_documents',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.Enum('invoice', 'receipt', 'bank_statement', 'credit_card_statement', 'payroll_report', 'other', name='document_type'), nullable=False),
    sa.Column('file_ref', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_client_id'), 'source_documents', ['client_id'], unique=False)
    op.create_index(op.f('ix_source_documents_content_hash'), 'source_documents', ['content_hash'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.Enum('intake_bookkeeper', 'reconciliation_close', 'cpa_review_copilot', 'reporting_insights', name='agent_type'), nullable=False),
    sa.Column('trigger', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', name='workflow_run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_client_id'), 'workflow_runs', ['client_id'], unique=False)
    op.create_table('accounting_periods',
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('close_status', sa.Enum('not_started', 'collecting_documents', 'processing', 'reconciling', 'waiting_for_client', 'ready_for_cpa_review', 'under_cpa_review', 'revision_required', 'approved', 'delivered', name='close_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engagement_id', 'period', name='uq_engagement_period')
    )
    op.create_index(op.f('ix_accounting_periods_engagement_id'), 'accounting_periods', ['engagement_id'], unique=False)
    op.create_table('extracted_document_data',
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('skill_name', sa.String(length=128), nullable=False),
    sa.Column('skill_version', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_document_data_source_document_id'), 'extracted_document_data', ['source_document_id'], unique=False)
    op.create_table('tool_invocations',
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('skill_version', sa.String(length=32), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_invocations_workflow_run_id'), 'tool_invocations', ['workflow_run_id'], unique=False)
    op.create_table('proposed_journal_entries',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_review', 'needs_client_information', 'needs_revision', 'approved', 'rejected', 'posted', 'reversed', name='entry_status'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['accounting_periods.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposed_journal_entries_client_id'), 'proposed_journal_entries', ['client_id'], unique=False)
    op.create_index(op.f('ix_proposed_journal_entries_period_id'), 'proposed_journal_entries', ['period_id'], unique=False)
    op.create_table('exception_records',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=True),
    sa.Column('related_entry_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('missing_document', 'unreadable_document', 'duplicate_invoice', 'unmatched_transaction', 'low_confidence_classification', 'personal_expense', 'owner_contribution_distribution', 'loan_transaction', 'fixed_asset_purchase', 'prepaid_expense', 'accrual', 'deferred_revenue', 'unusual_revenue', 'related_party_transaction', 'negative_balance', 'material_variance', 'new_vendor', 'new_revenue_stream', 'payroll_discrepancy', 'reconciliation_difference', 'possible_fraud_indicator', 'possible_tax_issue', 'possible_legal_issue', name='exception_type'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='exception_severity'), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', 'escalated', name='exception_status'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('detected_by', sa.String(length=64), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['accounting_periods.id'], ),
    sa.ForeignKeyConstraint(['related_entry_id'], ['proposed_journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exception_records_client_id'), 'exception_records', ['client_id'], unique=False)
    op.create_table('journal_entry_lines',
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('gl_account_id', sa.UUID(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['proposed_journal_entries.id'], ),
    sa.ForeignKeyConstraint(['gl_account_id'], ['gl_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entry_lines_entry_id'), 'journal_entry_lines', ['entry_id'], unique=False)
    op.create_table('review_decisions',
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('cpa_user_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('approved', 'rejected', 'revision_required', name='review_decision_type'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('mfa_verified', sa.Boolean(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cpa_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['proposed_journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_decisions_entry_id'), 'review_decisions', ['entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_decisions_entry_id'), table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_journal_entry_lines_entry_id'), table_name='journal_entry_lines')
    op.drop_table('journal_entry_lines')
    op.drop_index(op.f('ix_exception_records_client_id'), table_name='exception_records')
    op.drop_table('exception_records')
    op.drop_index(op.f('ix_proposed_journal_entries_period_id'), table_name='proposed_journal_entries')
    op.drop_index(op.f('ix_proposed_journal_entries_client_id'), table_name='proposed_journal_entries')
    op.drop_table('proposed_journal_entries')
    op.drop_index(op.f('ix_tool_invocations_workflow_run_id'), table_name='tool_invocations')
    op.drop_table('tool_invocations')
    op.drop_index(op.f('ix_extracted_document_data_source_document_id'), table_name='extracted_document_data')
    op.drop_table('extracted_document_data')
    op.drop_index(op.f('ix_accounting_periods_engagement_id'), table_name='accounting_periods')
    op.drop_table('accounting_periods')
    op.drop_index(op.f('ix_workflow_runs_client_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_source_documents_content_hash'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_client_id'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_gl_accounts_client_id'), table_name='gl_accounts')
    op.drop_table('gl_accounts')
    op.drop_index(op.f('ix_engagements_client_id'), table_name='engagements')
    op.drop_table('engagements')
    op.drop_index(op.f('ix_client_accounting_profiles_client_id'), table_name='client_accounting_profiles')
    op.drop_table('client_accounting_profiles')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_client_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_clients_organization_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('organizations')
    # ### end Alembic commands ###
