"""reconciliation and reporting tables

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-05 01:26:25.970025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_accounts',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('gl_account_id', sa.UUID(), nullable=False),
    sa.Column('account_type', sa.Enum('bank', 'credit_card', 'payroll_clearing', name='financial_account_type'), nullable=False),
    sa.Column('institution', sa.String(length=128), nullable=False),
    sa.Column('mask', sa.String(length=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['gl_account_id'], ['gl_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_accounts_client_id'), 'financial_accounts', ['client_id'], unique=False)
    op.create_table('executive_summaries',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('skill_version', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['accounting_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executive_summaries_client_id'), 'executive_summaries', ['client_id'], unique=False)
    op.create_index(op.f('ix_executive_summaries_period_id'), 'executive_summaries', ['period_id'], unique=False)
    op.create_table('financial_reports',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.Enum('income_statement', 'balance_sheet', 'cash_summary', name='financial_report_type'), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('generated_by', sa.String(length=64), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['accounting_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_reports_client_id'), 'financial_reports', ['client_id'], unique=False)
    op.create_index(op.f('ix_financial_reports_period_id'), 'financial_reports', ['period_id'], unique=False)
    op.create_table('imported_transactions',
    sa.Column('financial_account_id', sa.UUID(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('raw_ref', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['financial_account_id'], ['financial_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imported_transactions_financial_account_id'), 'imported_transactions', ['financial_account_id'], unique=False)
    op.create_table('reconciliations',
    sa.Column('financial_account_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'reconciled', 'discrepancy', name='reconciliation_status'), nullable=False),
    sa.Column('statement_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gl_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('difference', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['financial_account_id'], ['financial_accounts.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['accounting_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliations_financial_account_id'), 'reconciliations', ['financial_account_id'], unique=False)
    op.create_index(op.f('ix_reconciliations_period_id'), 'reconciliations', ['period_id'], unique=False)
    op.create_table('recommended_actions',
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['executive_summaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommended_actions_summary_id'), 'recommended_actions', ['summary_id'], unique=False)
    op.create_table('reconciliation_items',
    sa.Column('reconciliation_id', sa.UUID(), nullable=False),
    sa.Column('imported_transaction_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('matched', 'unmatched', 'uncleared', name='reconciliation_item_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['imported_transaction_id'], ['imported_transactions.id'], ),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['reconciliations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_items_reconciliation_id'), 'reconciliation_items', ['reconciliation_id'], unique=False)
    op.create_table('transaction_matches',
    sa.Column('imported_transaction_id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=True),
    sa.Column('match_method', sa.Enum('exact_amount_date', 'manual', name='transaction_match_method'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['proposed_journal_entries.id'], ),
    sa.ForeignKeyConstraint(['imported_transaction_id'], ['imported_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_matches_imported_transaction_id'), 'transaction_matches', ['imported_transaction_id'], unique=False)
    op.create_table('client_questions',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('exception_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('drafted', 'approved_for_sending', 'sent', 'answered', 'resolved', 'escalated', name='client_question_status'), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('drafted_by', sa.String(length=64), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['exception_id'], ['exception_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_questions_client_id'), 'client_questions', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_questions_client_id'), table_name='client_questions')
    op.drop_table('client_questions')
    op.drop_index(op.f('ix_transaction_matches_imported_transaction_id'), table_name='transaction_matches')
    op.drop_table('transaction_matches')
    op.drop_index(op.f('ix_reconciliation_items_reconciliation_id'), table_name='reconciliation_items')
    op.drop_table('reconciliation_items')
    op.drop_index(op.f('ix_recommended_actions_summary_id'), table_name='recommended_actions')
    op.drop_table('recommended_actions')
    op.drop_index(op.f('ix_reconciliations_period_id'), table_name='reconciliations')
    op.drop_index(op.f('ix_reconciliations_financial_account_id'), table_name='reconciliations')
    op.drop_table('reconciliations')
    op.drop_index(op.f('ix_imported_transactions_financial_account_id'), table_name='imported_transactions')
    op.drop_table('imported_transactions')
    op.drop_index(op.f('ix_financial_reports_period_id'), table_name='financial_reports')
    op.drop_index(op.f('ix_financial_reports_client_id'), table_name='financial_reports')
    op.drop_table('financial_reports')
    op.drop_index(op.f('ix_executive_summaries_period_id'), table_name='executive_summaries')
    op.drop_index(op.f('ix_executive_summaries_client_id'), table_name='executive_summaries')
    op.drop_table('executive_summaries')
    op.drop_index(op.f('ix_financial_accounts_client_id'), table_name='financial_accounts')
    op.drop_table('financial_accounts')
    # ### end Alembic commands ###
