"""
Bootstrap a development environment: one organization, one human CPA user,
the four AI service-account users (one per agent), one synthetic demo
client with a starter chart of accounts, and long-lived JWTs for the
service accounts.

This is the ONLY place service-account tokens are minted for local dev —
there is no HTTP login flow for them (see app/api/routes_auth.py). In a
real deployment these would instead be generated by the deployment
pipeline and injected via a secrets manager, never printed to a terminal.

Run with:
    python -m scripts.seed_dev
"""

from __future__ import annotations

import sys
from datetime import datetime, timezone

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.core.security import create_access_token, hash_password
from app.db.session import AdminSessionLocal
from app.models.accounting_period import AccountingPeriod, GLAccount
from app.models.accounting_profile import ClientAccountingProfile, Engagement
from app.models.enums import CloseStatus, GLAccountType, UserRole
from app.models.organization import Client, Organization
from app.models.user import User

DEMO_CPA_EMAIL = "cpa@datumai.dev"
DEMO_CPA_PASSWORD = "change-me-dev-only"  # noqa: S105 — dev fixture, not a real secret

AGENT_SEED_ACCOUNTS = [
    (UserRole.AI_INTAKE, "agent-intake@datumai.dev", "Intake Bookkeeper Agent"),
    (UserRole.AI_RECONCILIATION, "agent-reconciliation@datumai.dev", "Reconciliation & Close Agent"),
    (UserRole.AI_COPILOT, "agent-copilot@datumai.dev", "CPA Review Copilot"),
    (UserRole.AI_REPORTING, "agent-reporting@datumai.dev", "Reporting & Insights Agent"),
]

DEMO_COA = [
    ("1000", "Operating Cash", GLAccountType.ASSET),
    ("1200", "Accounts Receivable", GLAccountType.ASSET),
    ("1500", "Prepaid Expenses", GLAccountType.ASSET),
    ("2000", "Accounts Payable", GLAccountType.LIABILITY),
    ("2100", "Payroll Clearing", GLAccountType.LIABILITY),
    ("3000", "Owner's Equity", GLAccountType.EQUITY),
    ("4000", "Service Revenue", GLAccountType.REVENUE),
    ("6100", "Software and Subscriptions", GLAccountType.EXPENSE),
    ("6200", "Meals and Entertainment", GLAccountType.EXPENSE),
    ("6300", "Contract Labor", GLAccountType.EXPENSE),
    ("6400", "Office Supplies", GLAccountType.EXPENSE),
    ("6500", "Payroll Expense", GLAccountType.EXPENSE),
]


def _get_or_create_user(
    db: Session, *, email: str, full_name: str, role: UserRole, org_id, is_service_account: bool,
    password: str | None = None,
) -> User:
    existing = db.scalar(select(User).where(User.email == email))
    if existing:
        return existing
    user = User(
        organization_id=org_id,
        email=email,
        full_name=full_name,
        role=role,
        is_service_account=is_service_account,
        hashed_password=hash_password(password) if password else None,
    )
    db.add(user)
    db.flush()
    return user


def main() -> int:
    db = AdminSessionLocal()
    try:
        org = db.scalar(select(Organization).where(Organization.name == "Datum AI (dev)"))
        if not org:
            org = Organization(name="Datum AI (dev)")
            db.add(org)
            db.flush()

        cpa_user = _get_or_create_user(
            db,
            email=DEMO_CPA_EMAIL,
            full_name="Founder CPA",
            role=UserRole.CPA,
            org_id=org.id,
            is_service_account=False,
            password=DEMO_CPA_PASSWORD,
        )

        service_tokens: dict[str, str] = {}
        for role, email, name in AGENT_SEED_ACCOUNTS:
            user = _get_or_create_user(
                db, email=email, full_name=name, role=role, org_id=org.id, is_service_account=True
            )
            token = create_access_token(
                user_id=user.id, email=user.email, role=user.role, is_service_account=True
            )
            service_tokens[role.value] = token

        client = db.scalar(select(Client).where(Client.legal_name == "Riverside Consulting LLC"))
        if not client:
            client = Client(
                organization_id=org.id,
                legal_name="Riverside Consulting LLC",
                entity_type="LLC",
            )
            db.add(client)
            db.flush()

            db.add(
                ClientAccountingProfile(
                    client_id=client.id,
                    industry="Professional services / consulting",
                    coa_template="service_business_default",
                    materiality_threshold=500.00,
                    payroll_provider="Gusto",
                    revenue_model="Fixed-fee and hourly consulting engagements",
                    policy_approved_by=cpa_user.id,
                    policy_approved_at=datetime.now(timezone.utc),
                )
            )

            engagement = Engagement(client_id=client.id, service_tier="core_bookkeeping")
            db.add(engagement)
            db.flush()

            db.add(
                AccountingPeriod(
                    engagement_id=engagement.id,
                    period="2026-07",
                    close_status=CloseStatus.COLLECTING_DOCUMENTS,
                )
            )

            for code, name, account_type in DEMO_COA:
                db.add(GLAccount(client_id=client.id, code=code, name=name, account_type=account_type))

        db.commit()

        print("=" * 72)
        print("Datum AI dev environment seeded.")
        print("=" * 72)
        print(f"Organization:      {org.name} ({org.id})")
        print(f"Demo client:       Riverside Consulting LLC ({client.id})")
        print()
        print(f"CPA login:         {DEMO_CPA_EMAIL} / {DEMO_CPA_PASSWORD}")
        print("  -> POST /api/v1/auth/login to get a short-lived CPA token")
        print()
        print("AI agent service tokens (30-day expiry, dev only):")
        for role_value, token in service_tokens.items():
            print(f"  {role_value:20s} {token}")
        print()
        print("These are printed for local development convenience only.")
        print("A real deployment must inject these via a secrets manager,")
        print("never print or commit them.")
        return 0
    finally:
        db.close()


if __name__ == "__main__":
    sys.exit(main())
